services:
    netgen.openapi_ibexa.openapi.path_provider.page:
        class: Netgen\OpenApiIbexa\OpenApi\PathProvider\PagePathProvider
        arguments:
            - '@router'
            - '%netgen.openapi_ibexa.use_ibexa_full_view%'
        tags:
            - { name: netgen.openapi_ibexa.path_provider }

    netgen.openapi_ibexa.openapi.path_provider.location_children:
        class: Netgen\OpenApiIbexa\OpenApi\PathProvider\LocationChildrenPathProvider
        arguments:
            - '@router'
        tags:
            - { name: netgen.openapi_ibexa.path_provider }

    netgen.openapi_ibexa.openapi.path_provider.location_siblings:
        class: Netgen\OpenApiIbexa\OpenApi\PathProvider\LocationSiblingsPathProvider
        arguments:
            - '@router'
        tags:
            - { name: netgen.openapi_ibexa.path_provider }

    netgen.openapi_ibexa.openapi.path_provider.content_relations:
        class: Netgen\OpenApiIbexa\OpenApi\PathProvider\ContentRelationsPathProvider
        arguments:
            - '@router'
        tags:
            - { name: netgen.openapi_ibexa.path_provider }

    netgen.openapi_ibexa.openapi.path_provider.content_reverse_relations:
        class: Netgen\OpenApiIbexa\OpenApi\PathProvider\ContentReverseRelationsPathProvider
        arguments:
            - '@router'
        tags:
            - { name: netgen.openapi_ibexa.path_provider }
