services:
    netgen.openapi_ibexa.openapi.path_provider.page:
        class: Netgen\OpenApiIbexa\OpenApi\PathProvider\PagePathProvider
        tags:
            - { name: netgen.openapi_ibexa.path_provider }
