services:
    netgen.openapi_ibexa.openapi.factory:
        class: Netgen\OpenApiIbexa\OpenApi\OpenApiFactory
        arguments:
            - !tagged_iterator netgen.openapi_ibexa.path_provider
            - !tagged_iterator netgen.openapi_ibexa.schema_provider
