services:
    netgen.openapi_ibexa.command.dump_specification:
        class: Netgen\Bundle\OpenApiIbexaBundle\Command\DumpSpecificationCommand
        arguments:
            - '@netgen.openapi_ibexa.openapi.factory'
            - '@serializer'
        tags:
            - { name: console.command, command: netgen:openapi-ibexa:dump-spec }
