services:
    netgen.openapi_ibexa.controller.base:
        class: Symfony\Bundle\FrameworkBundle\Controller\AbstractController
        abstract: true
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]

    netgen.openapi_ibexa.controller.openapi.specification:
        class: Netgen\Bundle\OpenApiIbexaBundle\Controller\OpenApi\Specification
        parent: netgen.openapi_ibexa.controller.base
        arguments:
            - '@netgen.openapi_ibexa.openapi.factory'
            - '@serializer'
            - '%kernel.debug%'
        public: true
        tags:
            - { name: container.service_subscriber }

    netgen.openapi_ibexa.controller.page_view:
        class: Netgen\Bundle\OpenApiIbexaBundle\Controller\PageView
        parent: netgen.openapi_ibexa.controller.base
        arguments:
            - '@netgen.openapi_ibexa.ibexa.url_alias_location_resolver'
            - '@netgen_layouts.layout.resolver'
            - '@netgen.openapi_ibexa.page.factory'
            - '@netgen.openapi_ibexa.page.output.visitor.output_visitor'
        public: true
        tags:
            - { name: container.service_subscriber }

    netgen.openapi_ibexa.controller.ibexa_page_view:
        class: Netgen\Bundle\OpenApiIbexaBundle\Controller\IbexaPageView
        parent: netgen.ibexa_site_api.controller.base
        arguments:
            - '@netgen_layouts.layout.resolver'
            - '@netgen.openapi_ibexa.page.factory'
            - '@netgen.openapi_ibexa.page.output.visitor.output_visitor'
        public: true
        tags:
            - { name: container.service_subscriber }

    netgen.openapi_ibexa.controller.location_children:
        class: Netgen\Bundle\OpenApiIbexaBundle\Controller\LocationChildren
        parent: netgen.openapi_ibexa.controller.base
        arguments:
            - '@netgen.openapi_ibexa.page.output.visitor.output_visitor'
            - '%netgen.openapi_ibexa.default_limit%'
        public: true
        tags:
            - { name: container.service_subscriber }

    netgen.openapi_ibexa.controller.location_siblings:
        class: Netgen\Bundle\OpenApiIbexaBundle\Controller\LocationSiblings
        parent: netgen.openapi_ibexa.controller.base
        arguments:
            - '@netgen.openapi_ibexa.page.output.visitor.output_visitor'
            - '%netgen.openapi_ibexa.default_limit%'
        public: true
        tags:
            - { name: container.service_subscriber }

    netgen.openapi_ibexa.controller.content_relations:
        class: Netgen\Bundle\OpenApiIbexaBundle\Controller\ContentRelations
        parent: netgen.openapi_ibexa.controller.base
        arguments:
            - '@netgen.openapi_ibexa.page.output.visitor.output_visitor'
            - '%netgen.openapi_ibexa.default_limit%'
        public: true
        tags:
            - { name: container.service_subscriber }

    netgen.openapi_ibexa.controller.content_reverse_relations:
        class: Netgen\Bundle\OpenApiIbexaBundle\Controller\ContentReverseRelations
        parent: netgen.openapi_ibexa.controller.base
        arguments:
            - '@netgen.openapi_ibexa.page.output.visitor.output_visitor'
            - '%netgen.openapi_ibexa.default_limit%'
        public: true
        tags:
            - { name: container.service_subscriber }
