services:
    netgen.ibexa_openapi.controller.base:
        class: Symfony\Bundle\FrameworkBundle\Controller\AbstractController
        abstract: true
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]

    netgen.ibexa_openapi.controller.openapi.specification:
        class: Netgen\Bundle\IbexaOpenApiBundle\Controller\OpenApi\Specification
        parent: netgen.ibexa_openapi.controller.base
        arguments:
            - '@netgen.ibexa_openapi.openapi.factory'
            - '@serializer'
        public: true
        tags:
            - { name: container.service_subscriber }

    netgen.ibexa_openapi.controller.page.view:
        class: Netgen\Bundle\IbexaOpenApiBundle\Controller\Page\View
        parent: netgen.ibexa_openapi.controller.base
        arguments:
            - '@netgen.ibexa_site_api.load_service'
            - '@netgen.ibexa_openapi.page.factory'
            - '@netgen.ibexa_openapi.page.output.visitor.output_visitor'
            - '@serializer'
        public: true
        tags:
            - { name: container.service_subscriber }
