services:
    netgen.openapi_ibexa.controller.base:
        class: Symfony\Bundle\FrameworkBundle\Controller\AbstractController
        abstract: true
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]

    netgen.openapi_ibexa.controller.openapi.specification:
        class: Netgen\Bundle\OpenApiIbexaBundle\Controller\OpenApi\Specification
        parent: netgen.openapi_ibexa.controller.base
        arguments:
            - '@netgen.openapi_ibexa.openapi.factory'
            - '@serializer'
        public: true
        tags:
            - { name: container.service_subscriber }

    netgen.openapi_ibexa.controller.page.view:
        class: Netgen\Bundle\OpenApiIbexaBundle\Controller\Page\View
        parent: netgen.openapi_ibexa.controller.base
        arguments:
            - '@netgen.ibexa_site_api.load_service'
            - '@netgen_layouts.layout.resolver'
            - '@netgen.openapi_ibexa.page.factory'
            - '@netgen.openapi_ibexa.page.output.visitor.output_visitor'
            - '@serializer'
        public: true
        tags:
            - { name: container.service_subscriber }
