services:
    netgen.openapi_ibexa.controller.base:
        class: Symfony\Bundle\FrameworkBundle\Controller\AbstractController
        abstract: true
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]

    netgen.openapi_ibexa.controller.openapi.specification:
        class: Netgen\Bundle\OpenApiIbexaBundle\Controller\OpenApi\Specification
        parent: netgen.openapi_ibexa.controller.base
        arguments:
            - '@netgen.openapi_ibexa.openapi.factory'
            - '@serializer'
        public: true
        tags:
            - { name: container.service_subscriber }

    netgen.openapi_ibexa.controller.page.view:
        class: Netgen\Bundle\OpenApiIbexaBundle\Controller\Page\View
        parent: netgen.openapi_ibexa.controller.base
        arguments:
            - '@netgen.openapi_ibexa.ibexa.url_alias_location_resolver'
            - '@netgen_layouts.layout.resolver'
            - '@netgen.openapi_ibexa.page.factory'
            - '@netgen.openapi_ibexa.page.output.visitor.output_visitor'
            - '@serializer'
        public: true
        tags:
            - { name: container.service_subscriber }

    netgen.openapi_ibexa.controller.page.ibexa_view:
        class: Netgen\Bundle\OpenApiIbexaBundle\Controller\Page\IbexaView
        parent: netgen.ibexa_site_api.controller.base
        arguments:
            - '@netgen_layouts.layout.resolver'
            - '@netgen.openapi_ibexa.page.factory'
            - '@netgen.openapi_ibexa.page.output.visitor.output_visitor'
            - '@serializer'
        public: true
        tags:
            - { name: container.service_subscriber }

    netgen.openapi_ibexa.controller.page.location_children:
        class: Netgen\Bundle\OpenApiIbexaBundle\Controller\Page\LocationChildren
        parent: netgen.openapi_ibexa.controller.base
        arguments:
            - '@netgen.openapi_ibexa.page.output.visitor.output_visitor'
            - '@serializer'
            - '%netgen.openapi_ibexa.default_limit%'
        public: true
        tags:
            - { name: container.service_subscriber }

    netgen.openapi_ibexa.controller.page.content_relations:
        class: Netgen\Bundle\OpenApiIbexaBundle\Controller\Page\ContentRelations
        parent: netgen.openapi_ibexa.controller.base
        arguments:
            - '@netgen.openapi_ibexa.page.output.visitor.output_visitor'
            - '@serializer'
            - '%netgen.openapi_ibexa.default_limit%'
        public: true
        tags:
            - { name: container.service_subscriber }
