services:
    netgen.ibexa_openapi.openapi.path_provider.page:
        class: Netgen\IbexaOpenApi\OpenApi\PathProvider\PagePathProvider
        tags:
            - { name: netgen.ibexa_openapi.path_provider }
