services:
    netgen.ibexa_openapi.page.output.visitor.output_visitor:
        class: Netgen\IbexaOpenApi\Page\Output\OutputVisitor
        arguments:
            - !tagged_iterator netgen.ibexa_openapi.page.output.visitor

    netgen.ibexa_openapi.page.output.visitor.page:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\PageVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.layouts.layout:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\Layouts\LayoutVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.layouts.zone:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\Layouts\ZoneVisitor
        arguments:
            - '@netgen_layouts.api.service.block'
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.layouts.placeholder:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\Layouts\PlaceholderVisitor
        arguments:
            - '@netgen_layouts.api.service.block'
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.layouts.block.title:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\Layouts\Block\TitleBlockVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.layouts.block.list:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\Layouts\Block\ListBlockVisitor
        arguments:
            - '@netgen_layouts.collection.result.pagerfanta.factory'
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.layouts.block.component:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\Layouts\Block\ComponentBlockVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.layouts.block.placeholder:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\Layouts\Block\PlaceholderBlockVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.content:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\ContentVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.location:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\LocationVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field_value.binary_file:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldValue\BinaryFileFieldValueVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field_value.checkbox:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldValue\CheckboxFieldValueVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field_value.content_type_list:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldValue\ContentTypeListFieldValueVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field_value.date_and_time:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldValue\DateAndTimeFieldValueVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field_value.email_address:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldValue\EmailAddressFieldValueVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field_value.enhanced_link:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldValue\EnhancedLinkFieldValueVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field_value.enhanced_selection:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldValue\EnhancedSelectionFieldValueVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field_value.image:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldValue\ImageFieldValueVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field_value.integer:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldValue\IntegerFieldValueVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field_value.media:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldValue\MediaFieldValueVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field_value.metas:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldValue\MetasFieldValueVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field_value.relation:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldValue\RelationFieldValueVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field_value.relation_list:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldValue\RelationListFieldValueVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field_value.rich_text:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldValue\RichTextFieldValueVisitor
        arguments:
            - '@ibexa.richtext.converter.output.xhtml5'
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field_value.tags:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldValue\TagsFieldValueVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field_value.text_block:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldValue\TextBlockFieldValueVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field_value.text_line:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldValue\TextLineFieldValueVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }

    netgen.ibexa_openapi.page.output.visitor.site_api.field_value.url:
        class: Netgen\IbexaOpenApi\Page\Output\Visitor\SiteApi\FieldValue\UrlFieldValueVisitor
        tags:
            - { name: netgen.ibexa_openapi.page.output.visitor }
