system:
    default:
        page_schema:
            content:
                reference_name: SiteApi.Content
            location:
                reference_name: SiteApi.Location
            queries:
                reference_name: SiteApi.Queries
            layout:
                reference_name: Layouts.Layout
