netgen_openapi_ibexa_openapi_specification:
    path: /openapi/specification
    controller: netgen.openapi_ibexa.controller.openapi.specification
    methods: [GET]

netgen_openapi_ibexa_page_view:
    path: /page/{path}
    controller: netgen.openapi_ibexa.controller.page_view
    methods: [GET]
    defaults:
        path: ''

netgen_openapi_ibexa_location_children:
    path: /location/{locationId}/children/{maxPerPage}/{currentPage}
    controller: netgen.openapi_ibexa.controller.location_children
    methods: [GET]
    defaults:
        maxPerPage: '%netgen.openapi_ibexa.default_limit%'
        currentPage: 1

netgen_openapi_ibexa_location_siblings:
    path: /location/{locationId}/siblings/{maxPerPage}/{currentPage}
    controller: netgen.openapi_ibexa.controller.location_siblings
    methods: [GET]
    defaults:
        maxPerPage: '%netgen.openapi_ibexa.default_limit%'
        currentPage: 1

netgen_openapi_ibexa_content_relations:
    path: /content/{contentId}/relations/{fieldIdentifier}/{maxPerPage}/{currentPage}
    controller: netgen.openapi_ibexa.controller.content_relations
    methods: [GET]
    defaults:
        maxPerPage: '%netgen.openapi_ibexa.default_limit%'
        currentPage: 1

netgen_openapi_ibexa_content_reverse_relations:
    path: /content/{contentId}/reverse_relations/{fieldIdentifier}/{maxPerPage}/{currentPage}
    controller: netgen.openapi_ibexa.controller.content_reverse_relations
    methods: [GET]
    defaults:
        maxPerPage: '%netgen.openapi_ibexa.default_limit%'
        currentPage: 1

netgen_openapi_ibexa_site_api_query:
    path: /page/{contentId}/{locationId}/query/{queryIdentifier}
    controller: netgen.openapi_ibexa.controller.site_api_query
    methods: [GET]
