netgen_openapi_ibexa_openapi_specification:
    path: /openapi/specification
    controller: netgen.openapi_ibexa.controller.openapi.specification
    methods: [GET]

netgen_openapi_ibexa_page_view:
    path: /page/{path}
    controller: netgen.openapi_ibexa.controller.page.view
    methods: [GET]
    defaults:
        path: ''
